### ISSUE TITLE
Unable to clone repository

### ISSUE THREAD

**Issue by akashlomas-nsi** [cometchat-pro/javascript-angular-chat-app#11]
### Unable to clone the repository

> When I try to clone the repository (& I have tried with GIT CLI and GitHub for Desktop), I get this error.

Cloning into 'D:\A\javascript-angular-chat-app'...
remote: Enumerating objects: 1528, done.        
remote: Counting objects: 100% (1528/1528), done.        
remote: Compressing objects: 100% (1001/1001), done.        
remote: Total 1528 (delta 774), reused 1240 (delta 505), pack-reused 0        
Receiving objects: 100% (1528/1528), 6.92 MiB | 2.60 MiB/s, done.
Resolving deltas: 100% (774/774), done.
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Calls/CometChat-incoming-call/cometchat-incoming-call/cometchat-incoming-call.component.css: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Calls/CometChat-incoming-call/cometchat-incoming-call/cometchat-incoming-call.component.html: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Calls/CometChat-incoming-call/cometchat-incoming-call/cometchat-incoming-call.component.spec.ts: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Calls/CometChat-incoming-call/cometchat-incoming-call/cometchat-incoming-call.component.ts: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Calls/CometChat-outgoing-call/cometchat-outgoing-call/cometchat-outgoing-call.component.css: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Calls/CometChat-outgoing-call/cometchat-outgoing-call/cometchat-outgoing-call.component.html: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Calls/CometChat-outgoing-call/cometchat-outgoing-call/cometchat-outgoing-call.component.spec.ts: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Calls/CometChat-outgoing-call/cometchat-outgoing-call/cometchat-outgoing-call.component.ts: Filename too long
warning: unable to access 'CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Chats/CometChat-conversation-list-item/cometchat-conversation-list-item/.gitattributes': Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Chats/CometChat-conversation-list-item/cometchat-conversation-list-item/cometchat-conversation-list-item.component.css: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Chats/CometChat-conversation-list-item/cometchat-conversation-list-item/cometchat-conversation-list-item.component.html: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Chats/CometChat-conversation-list-item/cometchat-conversation-list-item/cometchat-conversation-list-item.component.spec.ts: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Chats/CometChat-conversation-list-item/cometchat-conversation-list-item/cometchat-conversation-list-item.component.ts: Filename too long
error: unable to create file CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Chats/CometChat-conversation-list-with-messages/cometchat-conversation-list-with-messages.module.ts: Filename too long
fatal: cannot create directory at 'CometChatWorkspace/projects/angular-chat-app/src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/Chats/CometChat-conversation-list-with-messages/cometchat-conversation-list-with-messages': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### Reproduction

> Run git clone https://github.com/cometchat-pro/cometchat-pro-angular-sample-app.git on command prompt
> After some time you should see an error as shared above.
> The same is true for GitHub for Desktop as well

<img width="527" alt="Screenshot 2021-05-12 152507" src="https://user-images.githubusercontent.com/80743508/117956030-47d9e400-b336-11eb-9bbd-4df7c947c176.png">

### Environment

> Windows 10 x64

**Comment by akashlomas-nsi** [comment]
Hi

Any updates, please?

Thanks

**Comment by PoojaShivane** [comment]
Hello @akashlomas-nsi 

This issue is specifically related to windows, 
you can run the following command before cloning the Repo. 
`git config --global core.longpaths true`

and then try cloning
`git clone https://github.com/cometchat-pro/cometchat-pro-angular-sample-app.git`
